In [23]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import pandas as pd
movies = pd.read_csv('annimation_movies.csv', encoding= 'unicode_escape')
credits = pd.read_csv('annimation_credits.csv', encoding= 'unicode_escape')

In [24]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",24-11-2010,591794936,100,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
1,200000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",NaN,62211,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 5984,...",en,Monsters University,A look at the relationship between Mike and Su...,89.186492,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",20-06-2013,743559607,104,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,School never looked this scary.,Monsters University,7.0,3528
2,200000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/toystory/,10193,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 3616,...",en,Toy Story 3,"Woody, Buzz, and the rest of Andy's toys haven...",59.995418,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-06-2010,1066969703,103,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,No toy gets left behind.,Toy Story 3,7.6,4597
3,207000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",NaN,254,"[{""id"": 774, ""name"": ""film business""}, {""id"": ...",en,King Kong,"In 1933 New York, an overly ambitious movie pr...",61.226010,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...","[{""iso_3166_1"": ""NZ"", ""name"": ""New Zealand""}, ...",14-12-2005,550000000,187,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The eighth wonder of the world.,King Kong,6.6,2337
4,175000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...",http://movies.disney.com/inside-out,150540,"[{""id"": 1566, ""name"": ""dream""}, {""id"": 6513, ""...",en,Inside Out,"Growing up can be a bumpy road, and it's no ex...",128.655964,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",09-06-2015,857611174,94,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Meet the little voices inside your head.,Inside Out,8.0,6560

In [25]:
credits.head()

,movie_id,title,cast,crew
0,38757,Tangled,"[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
1,62211,Monsters University,"[{""cast_id"": 6, ""character"": ""Michael ""Mike"" W...","[{""credit_id"": ""52fe4675c3a368484e091e53"", ""de..."
2,10193,Toy Story 3,"[{""cast_id"": 6, ""character"": ""Woody (voice)"", ...","[{""credit_id"": ""5770143fc3a3683733000f3a"", ""de..."
3,254,King Kong,"[{""cast_id"": 5, ""character"": ""Ann Darrow"", ""cr...","[{""credit_id"": ""52fe422ec3a36847f800a1d7"", ""de..."
4,150540,Inside Out,"[{""cast_id"": 4, ""character"": ""Joy (voice)"", ""c...","[{""credit_id"": ""56098866c3a368681000003a"", ""de..."

In [26]:
movies = movies.merge(credits,on='title')

In [27]:

# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [28]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,38757,Tangled,When the kingdom's most wanted-and most charmi...,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...","[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...","[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."

In [29]:
movies.dropna(inplace=True)
movies.duplicated().sum()
movies.iloc[0].genres

'[{"id": 16, "name": "Animation"}, {"id": 10751, "name": "Family"}]'

In [30]:
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [31]:
movies['genres'] = movies['genres'].apply(convert)

In [32]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,38757,Tangled,When the kingdom's most wanted-and most charmi...,"[Animation, Family]","[hostage, magic, horse, fairy tale, musical, p...","[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
1,62211,Monsters University,A look at the relationship between Mike and Su...,"[Animation, Family]","[monster, dormitory, games, animation, best fr...","[{""cast_id"": 6, ""character"": ""Michael ""Mike"" W...","[{""credit_id"": ""52fe4675c3a368484e091e53"", ""de..."
2,10193,Toy Story 3,"Woody, Buzz, and the rest of Andy's toys haven...","[Animation, Family, Comedy]","[hostage, college, toy, barbie, animation, esc...","[{""cast_id"": 6, ""character"": ""Woody (voice)"", ...","[{""credit_id"": ""5770143fc3a3683733000f3a"", ""de..."
3,254,King Kong,"In 1933 New York, an overly ambitious movie pr...","[Adventure, Drama, Action]","[film business, screenplay, show business, fil...","[{""cast_id"": 5, ""character"": ""Ann Darrow"", ""cr...","[{""credit_id"": ""52fe422ec3a36847f800a1d7"", ""de..."
4,150540,Inside Out,"Growing up can be a bumpy road, and it's no ex...","[Drama, Comedy, Animation, Family]","[dream, cartoon, imaginary friend, animation, ...","[{""cast_id"": 4, ""character"": ""Joy (voice)"", ""c...","[{""credit_id"": ""56098866c3a368681000003a"", ""de..."

In [39]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [41]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L 
movies['crew'] = movies['crew'].apply(fetch_director)

In [43]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
3,254,King Kong,"In 1933 New York, an overly ambitious movie pr...","[Adventure, Drama, Action]","[film business, screenplay, show business, fil...","[{""",[Peter Jackson]
14,11544,Lilo & Stitch,A lonely Hawaiian girl named Lilo is being rai...,"[Animation, Family]","[sister sister relationship, extraterrestrial ...","[{""","[Chris Sanders, Dean DeBlois]"
24,9444,Anastasia,This animated adventure retells the story of t...,"[Animation, Family]","[tzar, musical, russian revolution, train expl...","[{""","[Gary Goldman, Don Bluth]"
11,10567,Dinosaur,An orphaned dinosaur raised by lemurs joins an...,"[Animation, Family]","[cataclysm, asteroid, leader, comet, animation...","[{""","[Ralph Zondag, Eric Leighton]"
16,10715,Looney Tunes: Back in Action,Bugs Bunny and Daffy Duck are up to their feud...,"[Animation, Comedy, Family]","[spy, duck, bunny, wretch, film industry, live...","[{""",[Joe Dante]

In [44]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [45]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [46]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [47]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,38757,Tangled,"[When, the, kingdom's, most, wanted-and, most,...","[Animation, Family]","[hostage, magic, horse, fairytale, musical, pr...","[[, {, ""]","[ByronHoward, NathanGreno]"

In [48]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords']  + movies['crew']

In [49]:
new_df = movies[['movie_id','title','tags']]
new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

C:\Users\SANJOY\AppData\Local\Temp/ipykernel_18832/2174986103.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

In [50]:
new_df['tags'] = new_df['tags'].apply(lambda x :x.lower())

C:\Users\SANJOY\AppData\Local\Temp/ipykernel_18832/678442651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x :x.lower())

In [51]:
new_df['tags'][0]

"when the kingdom's most wanted-and most charming-bandit flynn rider hides out in a mysterious tower, he's taken hostage by rapunzel, a beautiful and feisty tower-bound teen with 70 feet of magical, golden hair. flynn's curious captor, who's looking for her ticket out of the tower where she's been locked away for years, strikes a deal with the handsome thief and the unlikely duo sets off on an action-packed escapade, complete with a super-cop horse, an over-protective chameleon and a gruff gang of pub thugs. animation family hostage magic horse fairytale musical princess animation tower blondewoman selfishness healingpower basedonfairytale duringcreditsstinger healinggift animalsidekick byronhoward nathangreno"

In [52]:
new_df.head()

,movie_id,title,tags
0,38757,Tangled,when the kingdom's most wanted-and most charmi...
1,62211,Monsters University,a look at the relationship between mike and su...
2,10193,Toy Story 3,"woody, buzz, and the rest of andy's toys haven..."
3,254,King Kong,"in 1933 new york, an overly ambitious movie pr..."
4,150540,Inside Out,"growing up can be a bumpy road, and it's no ex..."

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [54]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [55]:
vectors[0]

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0], dtype=int64)

In [56]:
cv.get_feature_names()

['1933',
 '3d',
 '70',
 'accepts',
 'accidentally',
 'accompanied',
 'action',
 'adjust',
 'adoption',
 'adopts',
 'adventure',
 'adventures',
 'adventurous',
 'advise',
 'aftercreditsstinger',
 'ages',
 'aided',
 'alessandrocarloni',
 'alex',
 'alien',
 'alienlife',
 'alienphenomenons',
 'alike',
 'ambitious',
 'american',
 'anastasia',
 'ancientchina',
 'ancientegypt',
 'andy',
 'anger',
 'animal',
 'animals',
 'animalsidekick',
 'animated',
 'animation',
 'anna',
 'answered',
 'anthonystacchi',
 'anthropomorphism',
 'ape',
 'apple',
 'arbuckle',
 'archibald',
 'arduous',
 'arendelle',
 'army',
 'arrives',
 'aside',
 'aspirations',
 'aspiring',
 'asteroid',
 'attempt',
 'attempts',
 'attention',
 'attract',
 'attracting',
 'audiences',
 'award',
 'away',
 'awesomeness',
 'bagheera',
 'baloo',
 'band',
 'bandit',
 'bands',
 'barbie',
 'barnyard',
 'barrycook',
 'basedonfairytale',
 'basedonnovel',
 'battle',
 'bear',
 'bearded',
 'beasts',
 'beat',
 'beautiful',
 'begin',
 'bellamy',
 'beloved',
 'bensharpsteen',
 'bent',
 'best',
 'bestfriend',
 'betrayal',
 'better',
 'betterment',
 'bibobergeron',
 'big',
 'bitter',
 'black',
 'blind',
 'blondewoman',
 'blood',
 'blue',
 'boisterous',
 'bound',
 'boundlessly',
 'bovine',
 'box',
 'boxtrolls',
 'boy',
 'brave',
 'bravery',
 'bring',
 'brings',
 'british',
 'bros',
 'bubbles',
 'buddy',
 'bugs',
 'bumpy',
 'bunny',
 'businessman',
 'buzz',
 'byronhoward',
 'called',
 'canine',
 'captain',
 'captor',
 'capture',
 'care',
 'carlo',
 'carlossaldanha',
 'carnival',
 'cartoon',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'center',
 'central',
 'certain',
 'chameleon',
 'change',
 'changed',
 'characters',
 'charming',
 'chester',
 'chicken',
 'chickenfarm',
 'chickens',
 'childprodigy',
 'children',
 'china',
 'chinese',
 'chosen',
 'chrisbuck',
 'chrissanders',
 'chriswedge',
 'circus',
 'city',
 'clean',
 'closer',
 'cobra',
 'codycameron',
 'coerces',
 'cojote',
 'collection',
 'college',
 'come',
 'comedy',
 'comes',
 'comet',
 'company',
 'competition',
 'complete',
 'computer',
 'conflict',
 'conradvernon',
 'conscience',
 'consistently',
 'continuing',
 'contract',
 'control',
 'cool',
 'cop',
 'copperbottom',
 'coronation',
 'corp',
 'country',
 'courage',
 'course',
 'coveted',
 'cow',
 'cracking',
 'crane',
 'crashing',
 'crazy',
 'create',
 'created',
 'creates',
 'creature',
 'creatures',
 'crew',
 'cricket',
 'crush',
 'cub',
 'curious',
 'curse',
 'cutlass',
 'czar',
 'dad',
 'daffy',
 'dance',
 'danger',
 'dangerous',
 'danscanlon',
 'daughter',
 'day',
 'daycare',
 'days',
 'deadparents',
 'deal',
 'deandeblois',
 'death',
 'decide',
 'decided',
 'deep',
 'delivery',
 'destiny',
 'destroys',
 'destruction',
 'diabolical',
 'die',
 'differences',
 'different',
 'dinosaur',
 'directed',
 'disappears',
 'disastrous',
 'discovers',
 'discovery',
 'disguises',
 'disgust',
 'dishonesty',
 'dj',
 'doesn',
 'dog',
 'donbluth',
 'doom',
 'dormitory',
 'dr',
 'dragon',
 'drake',
 'drama',
 'dream',
 'dreams',
 'dredge',
 'duck',
 'duo',
 'duringcreditsstinger',
 'dystopia',
 'easy',
 'effort',
 'egypt',
 'elephant',
 'elliott',
 'elsa',
 'embarks',
 'emotion',
 'emotions',
 'empress',
 'encounter',
 'encounters',
 'end',
 'england',
 'ensues',
 'ensuring',
 'enthusiastic',
 'epic',
 'ericdarnell',
 'ericleighton',
 'escapade',
 'escape',
 'escort',
 'eternal',
 'europe',
 'eventual',
 'everyday',
 'evil',
 'exception',
 'exotic',
 'exoticisland',
 'explodingtrain',
 'exterminator',
 'extraterrestrialtechnology',
 'face',
 'facing',
 'fairy',
 'fairytale',
 'fallen',
 'family',
 'fantasy',
 'farm',
 'farmer',
 'farmers',
 'fat',
 'fate',
 'father',
 'fatherdaughterrelationship',
 'fathersonrelationship',
 'fear',
 'feet',
 'feisty',
 'fellow',
 'feralchild',
 'feuding',
 'fiddle',
 'figaro',
 'fight',
 'fighting',
 'film',
 'filmbusiness',
 'filmindustry',
 'filmmaking',
 'filmproducer',
 'finally',
 'finding',
 'finds',
 'firstlove',
 'fish',
 'flee',
 'flint',
 'flynn',
 'foggy',
 'follows',
 'food',
 'forced',
 'forces',
 'foreignlanguageadaptation',
 'forest',
 'form',
 'francisco',
 'free',
 'freedom',
 'friend',
 'friends',
 'friendship',
 'fu',
 'funny',
 'furious',
 'gags',
 'galaxy',
 'games',
 'gang',
 'garfield',
 'garygoldman',
 'gate',
 'genius',
 'georgewashington',
 'geppetto',
 'gets',
 'giant',
 'ginger',
 'giraffe',
 'girl',
 'gloria',
 'golden',
 'good',
 'grahamannable',
 'granddaughter',
 'grandmother',
 'great',
 'group',
 'growing',
 'growingup',
 'grown',
 'gruff',
 'guard',
 'guess',
 'guided',
 'hair',
 'hamiltonluske',
 'hampered',
 'handsome',
 'haplessly',
 'happens',
 'haven',
 'having',
 'hawaii',
 'hawaiian',
 'hayward',
 'headquarters',
 'healinggift',
 'healingpower',
 'hears',
 'heart',
 'held',
 'help',
 'hero',
 'heroes',
 'hides',
 'high',
 'hilarious',
 'hippo',
 'hired',
 'history',
 'holds',
 'holiday',
 'home',
 'homeland',
 'hope',
 'hopelessly',
 'horse',
 'horton',
 'hostage',
 'houghton',
 'house',
 'hugely',
 'human',
 'humans',
 'humor',
 'hungry',
 'huns',
 'ice',
 'idol',
 'imaginaryfriend',
 'immediately',
 'impaired',
 'imperial',
 'important',
 'impossible',
 'imposters',
 'impress',
 'improbable',
 'inanimateobjectscomingtolife',
 'indigenous',
 'industries',
 'inherited',
 'inside',
 'instructs',
 'intelligence',
 'invading',
 'inventor',
 'inventors',
 'invitation',
 'iq',
 'irreverent',
 'island',
 'italy',
 'jackass',
 'james',
 'jeffnewitt',
 'jenniferlee',
 'jenniferyuhnelson',
 'jiminy',
 'jimmy',
 'jimmyhayward',
 'job',
 'joedante',
 'johnstevenson',
 'join',
 'joined',
 'joins',
 'jon',
 'jonfavreau',
 'journey',
 'joy',
 'julian',
 'jumba',
 'jungle',
 'just',
 'kate',
 'kevin',
 'key',
 'khan',
 'kids',
 'king',
 'kingdom',
 'kong',
 'krispearn',
 'kristoff',
 'kung',
 'kungfu',
 'lady',
 'lasagna',
 'lasagne',
 'lazy',
 'lead',
 'leader',
 'leading',
 'learns',
 'leave',
 'leeunkrich',
 'left',
 'legendary',
 'lemur',
 'lemurs',
 'lenny',
 'level',
 'li',
 'lie',
 'life',
 'like',
 'lilo',
 'lion',
 'listens',
 'little',
 'live',
 'liveactionandanimation',
 'living',
 'liz',
 'locked',
 'london',
 'londonengland',
 'lonely',
 'look',
 'looking',
 'lose',
 'lost',
 'lot',
 'love',
 'lover',
 'loves',
 'luck',
 'luxuriantly',
 'luxury',
 'machine',
 'mad',
 'madagascar',
 'madness',
 'magic',
 'magical',
 'main',
 'make',
 'making',
 'man',
 'mankind',
 'mantis',
 'maria',
 'markosborne',
 'martialarts',
 'marty',
 'master',
 'means',
 'melman',
 'men',
 'mentor',
 'menu',
 'meteorite',
 'midwest',
 'mike',
 'mind',
 'miniaturepeople',
 'mishaps',
 'mission',
 'missionofmurder',
 'mistakeinperson',
 'mistaken',
 'moderator',
 'moments',
 'monkey',
 'monkeys',
 'monkeywarrior',
 'monster',
 'monsters',
 'monte',
 'mountainclimber',
 'movie',
 'moving',
 'mowgli',
 'mr',
 'mrs',
 'mulan',
 'murderous',
 'mushu',
 'musical',
 'mutant',
 'mutation',
 'mysterious',
 'named',
 'names',
 'nani',
 'nathangreno',
 'navigate',
 'necessarily',
 'need',
 'nefarious',
 'nestinggrounds',
 'new',
 'newschool',
 'nickpark',
 'nobility',
 'noodle',
 'nose',
 'nutty',
 'obsolete',
 'odds',
 'odie',
 'offered',
 'olaf',
 'old',
 'older',
 'operates',
 'opposite',
 'order',
 'orphan',
 'orphanage',
 'orphaned',
 'oscar',
 'otis',
 'outcast',
 'overly',
 'owner',
 'owners',
 'packed',
 'panda',
 'panther',
 'parents',
 'paris',
 'park',
 'party',
 'peace',
 'peasant',
 'penguins',
 'personification',
 'petedocter',
 'peterhewitt',
 'peterjackson',
 'peterlord',
 'pickles',
 'pie',
 'piemachine',
 'pinocchio',
 'pirate',
 'place',
 'places',
 'played',
 'playing',
 'pleasure',
 'po',
 'pool',
 'pop',
 'positive',
 'prehistoric',
 'prehistoricadventure',
 'prehistoriccreature',
 'prehistoricegg',
 'prehistorictimes',
 'president',
 'princess',
 'prodigy',
 'producer',
 'protective',
 'prove',
 'proving',
 'pub',
 'puppet',
 'queen',
 'quest',
 'race',
 'rag',
 'raised',
 'ralphzondag',
 'rapunzel',
 'rarely',
 'rasputin',
 'ratchet',
 'real',
 'realize',
 'realizes',
 'really',
 'rebel',
 'recover',
 'regal',
 'reindeer',
 'relationship',
 'releases',
 'remake',
 'repressed',
 'rest',
 'restaurant',
 'restoring',
 'retells',
 'return',
 'reward',
 'rider',
 'right',
 'riley',
 'rivalry',
 'rivals',
 'road',
 'robletterman',
 'robminkoff',
 'robot',
 'rocky',
 'rodney',
 'romanov',
 'rooster',
 'russia',
 'russian',
 'russianrevolution',
 'sadness',
 'sam',
 'san',
 'sancturary',
 'save',
 'scary',
 'school',
 'sciencefiction',
 'scientist',
 'screenplay',
 'sea',
 'seas',
 'second',
 'secret',
 'secretlove',
 'security',
 'seeking',
 'seemingly',
 'self',
 'selfishness',
 'sensei',
 'separated',
 'sequel',
 'sets',
 'setting',
 'sewers',
 'shang',
 'shark',
 'shere',
 'shifu',
 'ship',
 'shop',
 'shores',
 'showbusiness',
 'shower',
 'shrimpanzees',
 'sidekick',
 'sides',
 'sight',
 'sing',
 'sister',
 'sistersisterrelationship',
 'skeptical',
 'skull',
 'slacker',
 'slowly',
 'small',
 'smitten',
 'snake',
 'snatcher',
 'sneezing',
 'snow',
 'snowman',
 'social',
 'somewhat',
 'space',
 'species',
 'spirited',
 'spring',
 'spy',
 'stacked',
 'star',
 'starts',
 'stern',
 'steveoedekerk',
 'stitch',
 'stolen',
 'stop',
 'stopmotion',
 'storm',
 'story',
 'streets',
 'strikes',
 'stromboli',
 'strongwoman',
 'struggle',
 'studio',
 'stunt',
 'successful',
 'sulley',
 'super',
 'supernatural',
 'surprising',
 'survival',
 'sven',
 'tacodiles',
 'tag',
 'taken',
 'takes',
 'taking',
 'tale',
 'talkinganimal',
 'talkingdog',
 'talkingtoanimals',
 'tasked',
 'team',
 'technologies',
 'teddybear',
 'teen',
 'teenager',
 'temptations',
 'terror',
 'tested',
 'thanksgiving',
 'thief',
 'thing',
 'things',
 'thons',
 'threat',
 'threatened',
 'threats',
 'threattodeath',
 'thugs',
 'ticket',
 'tiger',
 'tigress',
 'time',
 'timeparadox',
 'timetravel',
 'timetraveler',
 'timhill',
 'tired',
 'tomboyish',
 'tommcgrath',
 'tonybancroft',
 'tower',
 'town',
 'toy',
 'toycomestolife',
 'toymaker',
 'toys',
 'toystory',
 'tracks',
 'trainexplosion',
 'training',
 'trains',
 'transforming',
 'transported',
 'travel',
 'traveling',
 'travels',
 'trek',
 'tries',
 'trio',
 'troll',
 'trouble',
 'troublemaker',
 'true',
 'try',
 'trying',
 'turkey',
 'turkeys',
 'turmoil',
 'turns',
 'turtle',
 'tweedy',
 'tzar',
 'underground',
 'unicorn',
 'university',
 'unlikely',
 'unlikelyfriendship',
 'unsleek',
 'uprooted',
 'valley',
 'vegetarian',
 'vet',
 'vice',
 'vickyjenson',
 'victorian',
 'village',
 'viper',
 'voiced',
 'wacky',
 'want',
 'wanted',
 'wants',
 'warner',
 'warns',
 'warrior',
 'watch',
 'way',
 'ways',
 'wb',
 'weld',
 'weren',
 'whistling',
 'white',
 'win',
 'winter',
 'wise',
 'wish',
 'wishes',
 'wolf',
 'womandirector',
 'won',
 'wooden',
 'woodenhead',
 'woody',
 'worker',
 'world',
 'worthy',
 'wretch',
 'wrong',
 'wuxia',
 'year',
 'years',
 'york',
 'young',
 'zebra',
 'zoo']

In [57]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [58]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\SANJOY\AppData\Local\Temp/ipykernel_18832/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [59]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

In [60]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
similarity

array([[1.        , 0.11877114, 0.14506471, 0.03329636, 0.06306562,
        0.0471521 , 0.11386021, 0.07463518, 0.06329207, 0.06827887,
        0.03878158, 0.10241831, 0.07658396, 0.09988907, 0.08547043,
        0.05056499, 0.03936479, 0.03263956, 0.1015453 , 0.10969086,
        0.0927837 , 0.06154575, 0.06502561, 0.04571503, 0.0805823 ,
        0.122279  , 0.04821183, 0.06898645, 0.03878158],
       [0.11877114, 1.        , 0.15161961, 0.05800148, 0.10985884,
        0.08213785, 0.13222789, 0.07800765, 0.11025331, 0.08920516,
        0.09007547, 0.17841031, 0.1000556 , 0.08700222, 0.17370208,
        0.08808303, 0.06857255, 0.0758098 , 0.12634967, 0.22292541,
        0.12930164, 0.10721125, 0.08495482, 0.09954315, 0.11697707,
        0.23430788, 0.08398388, 0.0858377 , 0.0675566 ],
       [0.14506471, 0.15161961, 1.        , 0.        , 0.10350983,
        0.06019293, 0.08075026, 0.07622159, 0.08079673, 0.10895341,
        0.06600984, 0.15253477, 0.12220593, 0.06375767, 0.09092412,
        0.0860663 , 0.08375315, 0.06944444, 0.11111111, 0.11669001,
        0.14213381, 0.07856742, 0.12451456, 0.07294802, 0.1028689 ,
        0.18731716, 0.10257624, 0.07548514, 0.13201967],
       [0.03329636, 0.05800148, 0.        , 1.        , 0.05279637,
        0.04605313, 0.05560325, 0.0874748 , 0.13246486, 0.12503908,
        0.0378777 , 0.07502345, 0.02804964, 0.02439024, 0.0208696 ,
        0.02469324, 0.01922366, 0.07969709, 0.02125256, 0.08035074,
        0.05437272, 0.02254174, 0.04763255, 0.10046151, 0.05902813,
        0.03582872, 0.        , 0.07219135, 0.01893885],
       [0.06306562, 0.10985884, 0.10350983, 0.05279637, 1.        ,
        0.07476672, 0.08024109, 0.05917263, 0.1505386 , 0.0676665 ,
        0.051245  , 0.10826639, 0.06071767, 0.06599546, 0.11293849,
        0.09354143, 0.05201565, 0.07763238, 0.08050765, 0.08696566,
        0.11769798, 0.06099375, 0.10310785, 0.07248804, 0.0745356 ,
        0.13572418, 0.08918826, 0.08594799, 0.051245  ],
       [0.0471521 , 0.08213785, 0.06019293, 0.04605313, 0.07476672,
        1.        , 0.12248699, 0.08258401, 0.05002345, 0.11804804,
        0.10727978, 0.11804804, 0.1853695 , 0.11513282, 0.05910828,
        0.04662524, 0.05444655, 0.04514469, 0.06019293, 0.12643043,
        0.1539981 , 0.04256283, 0.06745406, 0.04742231, 0.07430376,
        0.10147651, 0.04445542, 0.05452405, 0.03575993],
       [0.11386021, 0.13222789, 0.08075026, 0.05560325, 0.08024109,
        0.12248699, 1.        , 0.13294614, 0.09059536, 0.19003716,
        0.10074289, 0.13302601, 0.10657614, 0.18534416, 0.09515422,
        0.15011733, 0.08764963, 0.09690032, 0.11305037, 0.18317824,
        0.1239553 , 0.08564859, 0.1085895 , 0.17813089, 0.16447248,
        0.16335983, 0.07156563, 0.164577  , 0.04317552],
       [0.07463518, 0.07800765, 0.07622159, 0.0874748 , 0.05917263,
        0.08258401, 0.13294614, 1.        , 0.09501617, 0.17937941,
        0.06792356, 0.11211213, 0.07544932, 0.0874748 , 0.16840827,
        0.08856149, 0.05170877, 0.10004084, 0.09527699, 0.14408763,
        0.19500598, 0.08084521, 0.1494785 , 0.10508805, 0.08820935,
        0.12849851, 0.10555008, 0.14240153, 0.03396178],
       [0.06329207, 0.11025331, 0.08079673, 0.13246486, 0.1505386 ,
        0.05002345, 0.09059536, 0.09501617, 1.        , 0.05432757,
        0.04114321, 0.16298271, 0.06093569, 0.06623243, 0.12467841,
        0.09387731, 0.04176194, 0.06059754, 0.09233911, 0.10182424,
        0.07382537, 0.04897021, 0.11641284, 0.05456124, 0.11754794,
        0.14594091, 0.10229543, 0.05489057, 0.04114321],
       [0.06827887, 0.08920516, 0.10895341, 0.12503908, 0.0676665 ,
        0.11804804, 0.19003716, 0.17937941, 0.05432757, 1.        ,
        0.29127586, 0.17948718, 0.11503946, 0.1500469 , 0.06419407,
        0.12659242, 0.09855207, 0.17977312, 0.13074409, 0.16477051,
        0.22299787, 0.11556254, 0.1709352 , 0.15450786, 0.10087126,
        0.16531163, 0.09656091, 0.17764624, 0.07767356],
       [0.03878158, 0.09007547, 0.06600984, 0.0378777 , 0.051245  ,
        0.10727978, 0.10074289, 0.06792356, 0.04114321, 0.29127586,
        1.        , 0.09709195, 0.08712137, 0.09469425, 0.04861528,
        0.11504475, 0.05970814, 0.09901475, 0.11551721, 0.08318903,
        0.14777012, 0.070014  , 0.09246584, 0.10401019, 0.07639154,
        0.11128298, 0.05484543, 0.08968971, 0.05882353],
       [0.10241831, 0.17841031, 0.15253477, 0.07502345, 0.10826639,
        0.11804804, 0.13302601, 0.11211213, 0.16298271, 0.17948718,
        0.09709195, 1.        , 0.11503946, 0.10003126, 0.14978617,
        0.12659242, 0.09855207, 0.1470871 , 0.13074409, 0.16477051,
        0.27874734, 0.11556254, 0.09767726, 0.10300524, 0.12104551,
        0.23878347, 0.12070114, 0.13323468, 0.07767356],
       [0.07658396, 0.1000556 , 0.12220593, 0.02804964, 0.06071767,
        0.1853695 , 0.10657614, 0.07544932, 0.06093569, 0.11503946,
        0.08712137, 0.11503946, 1.        , 0.11219854, 0.0720023 ,
        0.17038855, 0.06632365, 0.12831623, 0.07332356, 0.12320822,
        0.21885689, 0.05184758, 0.10955821, 0.11553426, 0.13576885,
        0.14421499, 0.05415304, 0.08302258, 0.06534103],
       [0.09988907, 0.08700222, 0.06375767, 0.02439024, 0.06599546,
        0.11513282, 0.18534416, 0.0874748 , 0.06623243, 0.1500469 ,
        0.09469425, 0.10003126, 0.11219854, 1.        , 0.08347839,
        0.07407972, 0.05767098, 0.04781825, 0.06375767, 0.16070148,
        0.10874545, 0.04508348, 0.07144883, 0.10046151, 0.11805627,
        0.14331487, 0.04708816, 0.07219135, 0.0378777 ],
       [0.08547043, 0.17370208, 0.09092412, 0.0208696 , 0.11293849,
        0.05910828, 0.09515422, 0.16840827, 0.12467841, 0.06419407,
        0.04861528, 0.14978617, 0.0720023 , 0.08347839, 1.        ,
        0.08451543, 0.04934638, 0.12274756, 0.10910895, 0.16042224,
        0.11631053, 0.07715167, 0.06113544, 0.07163353, 0.08417938,
        0.16861332, 0.16116459, 0.07412493, 0.04861528],
       [0.05056499, 0.08808303, 0.0860663 , 0.02469324, 0.09354143,
        0.04662524, 0.15011733, 0.08856149, 0.09387731, 0.12659242,
        0.11504475, 0.12659242, 0.17038855, 0.07407972, 0.08451543,
        1.        , 0.07784989, 0.25819889, 0.12909944, 0.13558154,
        0.19266866, 0.09128709, 0.09644856, 0.1356127 , 0.09960238,
        0.16323216, 0.07150969, 0.1315587 , 0.0766965 ],
       [0.03936479, 0.06857255, 0.08375315, 0.01922366, 0.05201565,
        0.05444655, 0.08764963, 0.05170877, 0.04176194, 0.09855207,
        0.05970814, 0.09855207, 0.06632365, 0.05767098, 0.04934638,
        0.07784989, 1.        , 0.11306675, 0.08375315, 0.08444007,
        0.12856487, 0.10660036, 0.09385638, 0.09237755, 0.06203228,
        0.1129565 , 0.07422696, 0.0910385 , 0.05970814],
       [0.03263956, 0.0758098 , 0.06944444, 0.07969709, 0.07763238,
        0.04514469, 0.09690032, 0.10004084, 0.06059754, 0.17977312,
        0.09901475, 0.1470871 , 0.12831623, 0.04781825, 0.12274756,
        0.25819889, 0.11306675, 1.        , 0.05555556, 0.070014  ,
        0.24873417, 0.11785113, 0.06225728, 0.16413304, 0.06429306,
        0.14048787, 0.06154575, 0.16040591, 0.03713053],
       [0.1015453 , 0.12634967, 0.11111111, 0.02125256, 0.08050765,
        0.06019293, 0.11305037, 0.09527699, 0.09233911, 0.13074409,
        0.11551721, 0.13074409, 0.07332356, 0.06375767, 0.10910895,
        0.12909944, 0.08375315, 0.05555556, 1.        , 0.14002801,
        0.14213381, 0.07856742, 0.10376213, 0.08753762, 0.08572408,
        0.1717074 , 0.08206099, 0.08806599, 0.0825123 ],
       [0.10969086, 0.22292541, 0.11669001, 0.08035074, 0.08696566,
        0.12643043, 0.18317824, 0.14408763, 0.10182424, 0.16477051,
        0.08318903, 0.16477051, 0.12320822, 0.16070148, 0.16042224,
        0.13558154, 0.08444007, 0.070014  , 0.14002801, 1.        ,
        0.11941629, 0.07426107, 0.10461316, 0.09193289, 0.17285433,
        0.21639461, 0.07756315, 0.0951303 , 0.06239177],
       [0.0927837 , 0.12930164, 0.14213381, 0.05437272, 0.11769798,
        0.1539981 , 0.1239553 , 0.19500598, 0.07382537, 0.22299787,
        0.14777012, 0.27874734, 0.21885689, 0.10874545, 0.11631053,
        0.19266866, 0.12856487, 0.24873417, 0.14213381, 0.11941629,
        1.        , 0.15075567, 0.15927956, 0.18663084, 0.10965862,
        0.23961692, 0.10497278, 0.2092153 , 0.10555008],
       [0.06154575, 0.10721125, 0.07856742, 0.02254174, 0.06099375,
        0.04256283, 0.08564859, 0.08084521, 0.04897021, 0.11556254,
        0.070014  , 0.11556254, 0.05184758, 0.04508348, 0.07715167,
        0.09128709, 0.10660036, 0.11785113, 0.07856742, 0.07426107,
        0.15075567, 1.        , 0.13206764, 0.09284767, 0.09092412,
        0.16556654, 0.43519414, 0.1067521 , 0.0525105 ],
       [0.06502561, 0.08495482, 0.12451456, 0.04763255, 0.10310785,
        0.06745406, 0.1085895 , 0.1494785 , 0.11641284, 0.1709352 ,
        0.09246584, 0.09767726, 0.10955821, 0.07144883, 0.06113544,
        0.09644856, 0.09385638, 0.06225728, 0.10376213, 0.10461316,
        0.15927956, 0.13206764, 1.        , 0.11444694, 0.11527808,
        0.17492786, 0.0919601 , 0.05639399, 0.09246584],
       [0.04571503, 0.09954315, 0.07294802, 0.10046151, 0.07248804,
        0.04742231, 0.17813089, 0.10508805, 0.05456124, 0.15450786,
        0.10401019, 0.10300524, 0.11553426, 0.10046151, 0.07163353,
        0.1356127 , 0.09237755, 0.16413304, 0.08753762, 0.09193289,
        0.18663084, 0.09284767, 0.11444694, 1.        , 0.06753674,
        0.13527772, 0.09697623, 0.13876357, 0.0520051 ],
       [0.0805823 , 0.11697707, 0.1028689 , 0.05902813, 0.0745356 ,
        0.07430376, 0.16447248, 0.08820935, 0.11754794, 0.10087126,
        0.07639154, 0.12104551, 0.13576885, 0.11805627, 0.08417938,
        0.09960238, 0.06203228, 0.06429306, 0.08572408, 0.17285433,
        0.10965862, 0.09092412, 0.11527808, 0.06753674, 1.        ,
        0.17342199, 0.07597372, 0.08153327, 0.06111323],
       [0.122279  , 0.23430788, 0.18731716, 0.03582872, 0.13572418,
        0.10147651, 0.16335983, 0.12849851, 0.14594091, 0.16531163,
        0.11128298, 0.23878347, 0.14421499, 0.14331487, 0.16861332,
        0.16323216, 0.1129565 , 0.14048787, 0.1717074 , 0.21639461,
        0.23961692, 0.16556654, 0.17492786, 0.13527772, 0.17342199,
        1.        , 0.13834289, 0.1378617 , 0.19474521],
       [0.04821183, 0.08398388, 0.10257624, 0.        , 0.08918826,
        0.04445542, 0.07156563, 0.10555008, 0.10229543, 0.09656091,
        0.05484543, 0.12070114, 0.05415304, 0.04708816, 0.16116459,
        0.07150969, 0.07422696, 0.06154575, 0.08206099, 0.07756315,
        0.10497278, 0.43519414, 0.0919601 , 0.09697623, 0.07597372,
        0.13834289, 1.        , 0.06968683, 0.05484543],
       [0.06898645, 0.0858377 , 0.07548514, 0.07219135, 0.08594799,
        0.05452405, 0.164577  , 0.14240153, 0.05489057, 0.17764624,
        0.08968971, 0.13323468, 0.08302258, 0.07219135, 0.07412493,
        0.1315587 , 0.0910385 , 0.16040591, 0.08806599, 0.0951303 ,
        0.2092153 , 0.1067521 , 0.05639399, 0.13876357, 0.08153327,
        0.1378617 , 0.06968683, 1.        , 0.03363364],
       [0.03878158, 0.0675566 , 0.13201967, 0.01893885, 0.051245  ,
        0.03575993, 0.04317552, 0.03396178, 0.04114321, 0.07767356,
        0.05882353, 0.07767356, 0.06534103, 0.0378777 , 0.04861528,
        0.0766965 , 0.05970814, 0.03713053, 0.0825123 , 0.06239177,
        0.10555008, 0.0525105 , 0.09246584, 0.0520051 , 0.06111323,
        0.19474521, 0.05484543, 0.03363364, 1.        ]])

In [63]:
def recommend(movie):
    index = new_df[new_df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)

In [64]:
recommend('Tangled')

Toy Story 3
Barnyard
Monsters University
Frozen
Titan A.E.

In [65]:
import pickle
pickle.dump(new_df.to_dict(),open('cartoons_dict.pkl','wb'))
pickle.dump(similarity,open('cartoon_similarity.pkl','wb'))